export Login from './Login'
export Register from './Register'
export Dashboard from './Dashboard'
export Error404 from './Error404'
export AdminPanel from './AdminPanel'
export Department from './Department'
